name: File List
on: 
  push:
    branches:
      - master

jobs:
  build-file-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python make_file_list.py

      - name: Update File List
        uses: test-room-7/action-update-file@v1.6.0
        with:
            file-path: file_list.json
            commit-msg: Update resources
            branch: file_list
            github-token: ${{ secrets.GITHUB_TOKEN }}